### ISSUE TITLE
REST Interface review (ODD-190):  Making the interface more RESTy

### ISSUE THREAD

**Issue by RayPlante** [usnistgov/oar-rmm#4]
@deoyani 

I found the interface fairly straightforward to understand (though additional documentation would help in some places); however, the overall design could be made a bit more strictly consistent with true REST design.  For example, the API features the resource `/records/delete` to delete a record: one sends a GET request with the identifier of the record to delete given as a parameter.  The "canonical" way to provide this in the strict REST model, however, would be to have a resource called `/records/{id}` to which one would send a DELETE request.  Similarly, the `/records/save` resource would be handled instead by a POST request to the `/records/{id}` resource.

The way to think about this is as follows: a REST API provides CRUD access to _resources_, and a resource is just a remote object with some data (or more generally, _state_) associated with it.  Resources typically are _not_ operations or functions.  Here, perhaps, are the resources we want to make available via the API:
- catalog -- the full listing of the public products with catalog header metadata
- records -- the list of the public products (without the catalog header)
- a single record -- one of the records in the list, identified by an identifier
- resource APIs -- a list of available APIs
- taxonomy -- a list of scientific subject categories

Each resource has a URL path for refering to it.  If their are containment relationships between the resources, the paths can reflect this.  Thus our resources related to the catalog might be represented as follows:
- `/catalog`
- `/catalog/records`
- `/catalog/records/{id}`

For each of these, we then should ask which CRUD actions are needed (see also [wikipedia: Relationship between URL and HTTP methods](https://en.wikipedia.org/wiki/Representational_state_transfer#Relationship_between_URL_and_HTTP_methods)):
- `/catalog`
  - Create:  no
  - Retrieve:  yes, return the whole catalog (GET)
  - Update:  no (unless we're updating the header; we update individual records below)
  - Delete:  no, can't delete the catalog (even if it is empty).
- `/catalog/records`
  - Create:  yes; this is where one creates a new record (PUT)
  - Retrieve:  yes, return all records or views on the records (GET)
  - Update:  possibly, to do bulk updates to multiple records
  - Delete:  no; we'll keep an empty collection
- `/catalog/records/{id}`
  - Create:  no, unless one is creating a new subcollection
  - Retrieve:  yes, return an individual record (GET)
  - Update:  yes, update a record (POST)
  - Delete:  yes, delete the record (DELETE)

A question then remains on the best way to support a search interface.  One interpretation of the REST paradigm is to think of search results as a view on the records.  In this case, `/catalog/records` would replace `/records/search`; if no arguments are given, all records are returned.  

There reasonable reasons not to be completely strict in the REST paradigm.  In particular, sometimes it's a stretch to model a service as a stateful resource; maybe doing so makes the interface a little more opaque.  I would hope that we could start with a practice of being more strictly RESTful and then deviate as needed.

**Comment by deoyani** [comment]
Thanks for this feedback. I will update the api according to your suggestions. 
1. Relationship between URL and http method. 
 adding /catalog was an afterthought so I did not change /records to /catalog/records
2. Delete & Update are just space holders for now but can be done in the next build.
3. We can discuss about /save resource (insert record) how do we want it. 
4. Bulk Insert/updates are not complete yet but can be added in subsequent coding iterations

**Comment by RayPlante** [comment]
Thanks for the link on HATEOAS--that was new to me, but I like it quite a bit.  I look forward to playing with that.

**Comment by deoyani** [comment]
The code has been redesigned and this issue is solved.
